# coding: utf-8
"""
Script to automate who owes what for our online shopping.
Input: 	A .txt file generated by copying the confirmation email content
		into a text file (should also automate this, is there a
		Yahoo! Mail API ?)
		Asks who ordered which item
Output:	Calculates who owes who and how much ?
"""

import re

ocadoshop = "first food order ocado.txt"

def read_file(filepath):
	"""
	"""
	with open(filepath, "rU") as f:
		file = f.read()
		shop_items 	= re.findall(r'(^\d\d?) (.+?) £(\d\d?\.\d\d)', file, re.MULTILINE)
		other_costs = re.search(r'Delivery\s*£(\d\d?\.\d\d)\n^Voucher Saving\s*£(-?\d\d?.\d\d)', file, re.MULTILINE)

	delivery = float(other_costs.group(1))
	voucher  = float(other_costs.group(2))

	for i, shop_item in enumerate(shop_items, 1):
		amount, item, price = shop_item
		amount = int(amount)
		price  = float(price)	# need to make function to reformat it into a £price
	
	subtotal = sum([float(price) for amount, item, price in shop_items])
	total = subtotal + voucher + delivery
	print total

	# check that subtotal and total correspond to the text file

	

	return


def main():
	read_file(ocadoshop)
	return

if __name__ == '__main__':
	main()